version: '3.3'

networks:
  monitoring:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  api_gateway:
    image: api_gateway:latest 
    container_name: api_gateway
    ports:
      - "8080:8080"  
    environment:
      - MONITORING_ENABLED=${MONITORING_ENABLED}  
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  service-a:
    image: user_service  
    container_name: user_service
    ports:
      - "8081:8081"
    networks:
      - monitoring
