# prometheus.yml

global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: "api_gateway"
    metrics_path: "/metrics" 
    scrape_interval: 15s
    static_configs:
      - targets: ["api-gateway:8080"]
