apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  labels:
    app: user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: user-svc
          image: nuhman9260/hosp-connect-user-svc:latest
          ports:
            - containerPort: 50051
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: USER_DATABASE_URL
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: ADMIN_EMAIL
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: ADMIN_PASSWORD
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: REDIS_PORT
                
          - name: APPEMAIL
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: APPEMAIL
          - name: APPPASSWORD
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: APPPASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc-service
spec:
  selector:
    app: user-svc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
