name: CI/CD Pipeline for API Gateway

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Create .env file (optional if required for the build process)
    - name: Create .env file
      run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
        echo "MONITORING_ENABLED=true" >> .env
        echo "SERVER_PORT=:8080" >> .env
        echo "USER_GRPC_SERVER=hosp-connect-user-svc:50051" >> .env
        echo "APPT_GRPC_SERVER=hosp-connect-appt-svc:50052" >> .env
        echo "PAYMENT_GRPC_SERVER=hosp-connect-payment-svc:50053" >> .env

    # Step 4: Build the Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag hosp-connect-api-gateway:latest

    # Step 5: Tag and Push Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker tag hosp-connect-api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/hosp-connect-api-gateway:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hosp-connect-api-gateway:latest

    # Step 6: Set up kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # Step 7: Configure Kubernetes Context for DigitalOcean
    - name: Set up Kubernetes context
      env:
        DO_PAT: ${{ secrets.DO_PAT }}  # Your DigitalOcean Personal Access Token
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.98.0/doctl-1.98.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin/
        doctl auth init -t $DO_PAT
        doctl kubernetes cluster kubeconfig save k8s-1-31-1-do-4-lon1-1731914835868


    # Step 8: Update Kubernetes Deployment
    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/api-gateway-deployment api-gateway-container=${{ secrets.DOCKER_USERNAME }}/hosp-connect-api-gateway:latest
        kubectl rollout status deployment/api-gateway-deployment
