name: CI/CD Pipeline for API Gateway

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Create .env file (optional if required for the build process)
    - name: Create .env file
      run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
        echo "MONITORING_ENABLED=true" >> .env
        echo "SERVER_PORT=:8080" >> .env
        echo "USER_GRPC_SERVER=hosp-connect-user-svc:50051" >> .env
        echo "APPT_GRPC_SERVER=hosp-connect-appt-svc:50052" >> .env
        echo "PAYMENT_GRPC_SERVER=hosp-connect-payment-svc:50053" >> .env

    # Step 4: Build the Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag hosp-connect-api-gateway:latest

    # Step 5: Tag and Push Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker tag hosp-connect-api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/hosp-connect-api-gateway:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hosp-connect-api-gateway:latest
